language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U pyflakes
  - pip install -U pytest
  - pip install -r requirements.txt
  - pip list
script:
  - pyflakes --version && pyflakes pigskin/ setup.py
  - pytest --version && pytest tests/
sudo: false
