language: python
cache: pip
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -U .[test]
  - pip install -U codecov
  - pip install -r requirements.txt
  - pip list
script:
  - pyflakes --version && pyflakes pigskin/ setup.py
  - pytest --version && pytest --vcr-record=none --cov=pigskin/
  - codecov
sudo: false
